### ISSUE TITLE
Undefined symbol _OBJC_CLASS_$_RNNotifications"

### ISSUE THREAD

**Issue by josefheld** [wix/react-native-notifications#257] opened 2018-09-21 21:56 UTC
Hi, 
I think I followed the instructions carefully. Still I am getting this linker error.
Has anybody an idea what I am missing?

 Undefined symbols for architecture arm64:
 "_OBJC_CLASS_$_RNNotifications", referenced from:
       objc-class-ref in AppDelegate.o
 ld: symbol(s) not found for architecture arm64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)

Kind regards,
Josef

**Comment by PierreTrp** [comment] 2018-10-30 13:21
Same problem here..

`AppDelegate.m`

```
#import "RNNotifications.h"
#import "AppDelegate.h"
#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
#import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNative/AppCenterReactNative.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  [AppCenterReactNative register];  // Initialize AppCenter 

  [AppCenterReactNativeCrashes register];  // Initialize AppCenter crashes

  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:false];  // Initialize AppCenter analytics

  [AppCenterReactNative register];  // Initialize AppCenter

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"og666"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}


// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RNNotifications didRegisterUserNotificationSettings:notificationSettings];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}

// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
  [RNNotifications didReceiveRemoteNotification:notification];
}

// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RNNotifications didReceiveLocalNotification:notification];
}

@end
```

**Comment by PierreTrp** [comment] 2018-10-30 14:08
Fixed by adding `RNNotifications.xcodeproj` (from `node_modules/react-native-notifications/RNNotifications` into your `Libraries` folder of your main project in XCODE and then drag and drop the `libRNNotificaztion.a` file under tab `General` > `Linked Frameworks and Libraries`

**Comment by Kikketer** [comment] 2019-05-13 17:04
Still having the same issue, anyone have any ideas?

I've also tried the pods way of installing as well with `react-native link`, same results.

<img width="734" alt="Screen Shot 2019-05-13 at 12 03 32 PM" src="https://user-images.githubusercontent.com/958042/57640116-30b16180-7577-11e9-96a4-69da6e4a14c4.png">

**Comment by Kikketer** [comment] 2019-05-13 17:15
Any ideas why this would still be throwing this error?  The `react-native link` did the pod install at one point too but that failed.  Since then I have removed that pod and tried this "manual linking" method.  Still not working.

I can confirm this works fine in react-native version 0.57.x but does not work in 0.59.8

<img width="734" alt="Screen Shot 2019-05-13 at 12 03 32 PM" src="https://user-images.githubusercontent.com/958042/57640643-af5ace80-7578-11e9-9f9e-e4224afda065.png">

**Closed** 2019-07-24 11:25 UTC

**Comment by harveyconnor** [comment] 2019-11-01 05:54
Getting this with v3...

**Comment by Aurelienlajoinie** [comment] 2020-01-10 13:17
Got the same problem with v3 Beta :s
