### ISSUE TITLE
Firebase error when building project

### ISSUE THREAD

**Issue by augustosnk12** [wix/react-native-notifications#741] opened 2021-05-26 16:44 UTC
Hi there,

I'm trying to run my react native application but I'm receaving the following errors and I don't have any idea how to solve it. I'm using the last version of react-native-notifications (3.4.2). Any answer or solution would be very appreciated.

`F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\fcm\FcmToken.java:12: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid
F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\fcm\FcmToken.java:13: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\fcm\FcmToken.java:78: error: cannot find symbol
        FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(new OnSuccessListener<InstanceIdResult>() {
                                                                                                    ^
  symbol:   class InstanceIdResult
  location: class FcmToken
F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\fcm\FcmToken.java:80: error: cannot find symbol
            public void onSuccess(InstanceIdResult instanceIdResult) {
                                  ^
  symbol: class InstanceIdResult
F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\fcm\FcmToken.java:78: error: cannot find symbol
        FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(new OnSuccessListener<InstanceIdResult>() {
        ^
  symbol:   variable FirebaseInstanceId
  location: class FcmToken
Note: F:\ProjetosGit\gmex\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\core\notification\PushNotification.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

**Comment by augustosnk12** [comment] 2021-05-26 19:08
Update 1: If I remove the `Notifications.setNotificationChannel` and ` Notifications.registerRemoteNotifications()` it compiles, but I need to test if how it does affect my app.

**Comment by sdiaz** [comment] 2021-05-28 08:06
I have the same problem

java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:78)
        at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:68)
        at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleWork (FcmInstanceIdRefreshHandlerService.java:26)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path...

**Comment by sdiaz** [comment] 2021-05-28 08:18
@augustosnk12

If you don't need the latest firebase core, I recommend to downgrade react-native-firebase to 11.5.0 to get it back to work until an update to the new firebase

**Comment by augustosnk12** [comment] 2021-05-28 11:09
What solved my problem was removing the **_firebaseVersion = "+"_** from the **_android/build.gradle_** file. I still don't know what exactly is the cause of the problem but it's working now.

**Comment by williamsilveira45** [comment] 2021-05-28 20:33
Same problem here!

**Comment by Elprior** [comment] 2021-05-29 19:23
> @augustosnk12
> 
> If you don't need the latest firebase core, I recommend to downgrade react-native-firebase to 11.5.0 to get it back to work until an update to the new firebase

Same problem here.
Going back to 11.5.0 instead of 12.0.0 seems to fix the issue.
Thx!

**Comment by kesha-antonov** [comment] 2021-06-02 08:46
Same issue

**Comment by scott0228** [comment] 2021-06-18 02:33
Add the firebase-iid dependency:
```
dependencies {
    implementation "com.google.firebase:firebase-iid"
}
```

**Comment by DanielEliraz** [comment] 2021-06-24 10:47
Will be released soon

**Closed by DanielEliraz** 2021-06-24 10:47 UTC

**Comment by code-by** [comment] 2022-03-17 12:22
after installing `@react-native-firebase/app` 14.5.1 have build error
comment out line
`implementation 'com.google.firebase:firebase-analytics:17.3.0'`
resolve build problem, than uncomment and add
`implementation "com.google.firebase:firebase-iid"`
build passed successfully

**Comment by camboYY** [comment] 2022-06-17 10:56
Same problem here!
